### PR TITLE
 Item URL validation

### PR DESCRIPTION
**Pull request by hoyelo**

### CODE REVIEW

**Review by bf-affirm — APPROVED** [review]

**Comment by AmyBeall** [comment]
Will this send null as the item URL or not send the item URL

Also can we remove the validation for the file scheme? The behavior should be if the scheme is `file:///` the item url is null

**Comment by bf-affirm** [comment]
> Will this send null as the item URL or not send the item URL
> 
> Also can we remove the validation for the file scheme? The behavior should be if the scheme is `file:///` the item url is null

The item URL key will not be present in the dictionary/json - clients shouldn't expect it to be there. If they optionally look for it, then its value would be null.

**Comment by AmyBeall** [comment]
Can you dive into this more "If they optionally look for it, then its value would be null." What would optionally look for it mean in this case?

**Comment by bf-affirm** [comment]
> Can you dive into this more "If they optionally look for it, then its value would be null." What would optionally look for it mean in this case?

I need more context. But simple way to look at this:
do you need the item url to be in the json in any way? It won't be there.
Not being there or being set to null should have the same effect.

**Comment by AmyBeall** [comment]
Got it, thank you!

After doing testing it is better to leave it out rather than assign it to null

**Comment by AmyBeall** [comment]
@hoyelo can you just remove the specific file validation?

**Comment by hoyelo** [comment]
> @hoyelo can you just remove the specific file validation?

Removed.

**Pull request merged**
