### PR TITLE
Bug fix: Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value #136

### PR DESCRIPTION
**Pull request by ilabsvictor**

### CODE REVIEW

**Review by AlexanderGuntermann — APPROVED** [review]

**Comment by AlexanderGuntermann** [comment]
Hi @ilabsvictor any idea why the PR checks appear to be stuck here?

**Comment by hoyelo** [comment]
> Hi @ilabsvictor any idea why the PR checks appear to be stuck here?

Because I have been removed from Affirm, and the test.yml is running on my GitHub account, and my account does not have an available runner to execute.

**Comment by ilabsvictor** [comment]
> Hi @ilabsvictor any idea why the PR checks appear to be stuck here?

Because I have been removed from Affirm, and the test.yml is running on my GitHub account, and my account does not have an available runner to execute.

**Comment by dswenson32** [comment]
@AlexanderGuntermann do you know how we can resolve this for Victor? I don't know if he needs to be added back to the SDK repository?

**Comment by AlexanderGuntermann** [comment]
> > Hi @ilabsvictor any idea why the PR checks appear to be stuck here?
> 
> Because I have been removed from Affirm, and the test.yml is running on my GitHub account, and my account does not have an available runner to execute.

I went ahead and ran the tests locally for tests and ui-tests and both are passing ✅

**Pull request merged**
