### PR TITLE
When an ALA message returns an empty string the button should disappear from the view

### PR DESCRIPTION
**Pull request by hoyelo**

### CODE REVIEW

**Comment by hoyelo** [comment]
@AmyBeall  Please note this is the PR that addresses:
1. When an ALA message returns an empty string the button should disappear from the view

**Comment by AmyBeall** [comment]
@hoyelo @sichx  Hi, I keep getting an error while running this branch.
[ALAFixError.txt](https://github.com/Affirm/affirm-merchant-sdk-ios/files/3288536/ALAFixError.txt)

**Comment by hoyelo** [comment]
@AmyBeall Is this still because you didn't clean up the cache code? Pls try it and let me know whether it works.

**Comment by AmyBeall** [comment]
@hoyelo No it is not, I have given more information in an email

**Comment by hoyelo** [comment]
@AmyBeall Thanks, i think it has been fixed.

**Pull request merged**
