### PR TITLE
Add web font support

### PR DESCRIPTION
**Pull request by hoyelo**
@AmyBeall This PR supports the use of web fonts to render promotional message.

### CODE REVIEW

**Comment by AmyBeall** [comment]
@hoyelo @sichx will this support a local ttf file as well?

**Comment by sichx** [comment]
@AmyBeall I will confirm this with @hoyelo and also ask him to provide an example on including a local ttf file.

**Comment by hoyelo** [comment]
@AmyBeall I have updated this PR, it supports both local and remote fonts, you can check it in the example app.
Simulator_Screen_Shot_-_iPhone_XR_-_2019-08-01_at_14_26_10
If you want to know how to support local font, pls check the readme file, thanks!

**Comment by hoyelo** [comment]
@AmyBeall Also the swift example shows how to configure promo message using custom font and color.

**Comment by AmyBeall** [comment]
@hoyelo @sichx This works in the promo text implementation when using `[self.promotionalButton configureWithAmount:[NSDecimalNumber decimalNumberWithString:amountText] affirmLogoType:AffirmLogoTypeName affirmColor:AffirmColorTypeBlue  font:[UIFont fontWithName:@"AtlanticTime" size:20] textColor:[UIColor darkTextColor]];`
However the font does not render correctly when using the AffirmLogoTypeText, I tested this the same way using `[self.promotionalButton configureWithAmount:[NSDecimalNumber decimalNumberWithString:amountText] affirmLogoType:AffirmLogoTypeText affirmColor:AffirmColorTypeBlue  font:[UIFont fontWithName:@"AtlanticTime" size:20] textColor:[UIColor darkTextColor]];`

**Comment by hoyelo** [comment]
@AmyBeall The example app supports these fonts:
    Copperplate,
    "Heiti SC",
    "Apple SD Gothic Neo",
    Thonburi,
    "Gill Sans",
    "Marker Felt",
    "Hiragino Maru Gothic ProN",
    "Courier New",
    "Kohinoor Telugu",
    "Heiti TC",
    "Avenir Next Condensed",
    "Tamil Sangam MN",
    "Helvetica Neue",
    "Gurmukhi MN",
    "Open Sans Condensed",
    Georgia,
    "Times New Roman",
    "Sinhala Sangam MN",
    "Arial Rounded MT Bold",
    Kailasa,
    "Kohinoor Devanagari",
    "Kohinoor Bangla",
    "Chalkboard SE",
    "Apple Color Emoji",
    "PingFang TC",
    "Gujarati Sangam MN",
    "Geeza Pro",
    Damascus,
    Noteworthy,
    Avenir,
    Mishafi,
    "Academy Engraved LET",
    Futura,
    "Party LET",
    "Kannada Sangam MN",
    "Arial Hebrew",
    Farah,
    Arial,
    Chalkduster,
    Kefa,
    "Hoefler Text",
    Optima,
    Palatino,
    "Malayalam Sangam MN",
    "Al Nile",
    "Lao Sangam MN",
    "Bradley Hand",
    "Hiragino Mincho ProN",
    "PingFang HK",
    Helvetica,
    Courier,
    Cochin,
    "Trebuchet MS",
    "Devanagari Sangam MN",
    "Oriya Sangam MN",
    Rockwell,
    "Snell Roundhand",
    "Zapf Dingbats",
    "Bodoni 72",
    Verdana,
    "American Typewriter",
    "Avenir Next",
    Baskerville,
    "Khmer Sangam MN",
    Didot,
    "Savoye LET",
    "Bodoni Ornaments",
    Symbol,
    Charter,
    Menlo,
    "Noto Nastaliq Urdu",
    "Bodoni 72 Smallcaps",
    "DIN Alternate",
    Papyrus,
    "Hiragino Sans",
    "PingFang SC",
    "Myanmar Sangam MN",
    "Noto Sans Chakma",
    Zapfino,
    "Telugu Sangam MN",
    "Bodoni 72 Oldstyle",
    "Euphemia UCAS",
    "Bangla Sangam MN",
    "DIN Condensed"
To support 'AtlanticTime', you need to follow the steps:
1. Add the font files to your project (make sure that the files are targeted properly to your application)
2. Add the font files to yourApp-Info.plist

You also can check it in the readme file. (Note: pls check the branch 'font_support').

**Comment by AmyBeall** [comment]
Hi Victor,

I added the AtlanticTime font and as previously stated it worked fine when using the LogoName

Amy Beall | Channel Partner Engineer | Affirm

**Comment by hoyelo** [comment]
@AmyBeall I apologize for this, just found a little bug on text type, the message not be rendered with the font and color. Pls pull the branch, clean it before rebuild.

**Pull request merged**
