### PR TITLE
Add product modal methods in the example app

### PR DESCRIPTION
**Pull request by hoyelo**
Note: Package size updated.

### CODE REVIEW

**Comment by AmyBeall** [comment]
@hoyelo When triggering the modal, we should be able to configure the pageType, price, and an optional promoID

**Comment by hoyelo** [comment]
@AmyBeall pageType, price (amount) and optional promoID (promoId) had been added.

**Comment by hoyelo** [comment]
@AmyBeall Please check the latest commits on detecting close event.

**Comment by AmyBeall** [comment]
@bf-affirm please review this diff when you get a chance!

**Comment by bf-affirm** [comment]
LGTM!

**Pull request merged**
